### PR TITLE
🎂 Brief tidy up and some basic bug fixing

### PR DESCRIPTION
**Pull request by ollieread**
In this commit I've tidied up some of the code to bring it more inline with how Laravel works. 
I've done the following;

- Add FQNs to docblocks
- Fixed issue with incorrect server provider in `composer.json`
- Simplified functionality
- Made a few opcode based improvements
- Added some sanity checking
- Remove unnecessary overrides & overwrote types in class docblock
- Updated the `whereRaw` method to be more fluent (prevented typing issue)
- Added an implementation of `whereColumn`
- Reformated chunks of code to make it a bit tidier and easier to read

Some of the formatting, such as the space after the unary logical not operator may not be what you want. Let me know if you have a particular code style you want to adhere to.

### CODE REVIEW

**Comment by ollieread** [comment]
I've since added

- Support for order clauses in queries
- Support for the MongoDB schema builder, specifically index control

**Comment by jenssegers** [comment]
Not sure we need FQN docblocks. Phpstorm handles these perfectly without them.

**Comment by jenssegers** [comment]
Any chance you could split up the PR in a few smaller PR's? That would make it much easier to review and merge 🙏

**Comment by ollieread** [comment]
@jenssegers I went with FQN doclbocks as that's what Laravel uses through the codebase, I can swap those out though. I could split this into smaller PRs definitely. I sort of got ahead of myself.

**Comment by ollieread** [comment]
@jenssegers I've looked into splitting this out, but the problem is that I sort of did them all on top of each other, so splitting it out causes errors unless all PRs are accepted.

**Comment by jenssegers** [comment]
If you remove/split the FQN stuff the PR will probably be small enough already :)

**Comment by trq** [comment]
> Not sure we need FQN docblocks. Phpstorm handles these perfectly without them.

PhpStorm won't handle these unless they are imported (use) or are in the same namespace as the current class.

I should add that I haven't tested this with this code, but I just know from experience in other code that this is how PhpStorm works.

**Comment by ollieread** [comment]
@jenssegers @trq Can confirm, PHPStorm will throw a fit and complain about them if they aren't valid. It's worth noting that the reason I started changing them was that PHPStorm was angry, and drew my attention to them.

I will split this PR out when I get chance, apologies, things have been real busy lately.
It's also worth noting that if I split out the FQN stuff, any changes will conflict with the later changes I made, which actually add to the functionality. Cherry picking to branches isn't really going to work here. I'll probably branch, reset master, and then just recreate the changes.

**Pull request closed without merging**
